---
- name: Manage GNS3 devices
  hosts: gns-ios
  gather_facts: false
  connection: local

  vars:
    cli:
      username: carlo
      password: cisco

  tasks:
    - name: enable ospf
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - router-id 192.168.122.76
          - network 0.0.0.0 255.255.255.255 area 0

      register: print_output

    - debug: var=print_output

    - name: Switch specific configs
  hosts: gns3-switches
  gather_facts: false
  connection: local

  vars:
    cli:
      username: carlo
      password: cisco
  tasks:
    - name: Create VLANs
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        lines:
          - vlan 2
          - vlan 3
          - vlan 4
          - vlan 5

      register: print_output

    - debug: var=print_output